{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'hello')", "trace": "self = <pyrunner.test_pytest.TestClass object at 0x1078ce7f0>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"hello\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'hello')\n\npyrunner/test_pytest.py:38: AssertionError"}, "attachments": [{"name": "stdout", "source": "7b25cae1-d0bb-4ff3-942f-249b13ae730a-attachment.txt", "type": "text/plain"}], "start": 1594572844174, "stop": 1594572844174, "uuid": "94aa2494-7037-4f63-b05a-3927c745aed0", "historyId": "eee204faf163f7e40136f155778226ae", "testCaseId": "3c6259ae3af16af292d5cdd8e763e575", "fullName": "pyrunner.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "pyrunner"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "192.168.2.101"}, {"name": "thread", "value": "4627-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pyrunner.test_pytest"}]}